parameters:
    flash_error_alias: "error"
    flash_success_alias: "success"
    flash_warning_alias: "warning"
    flash_info_alias: "info"
    upload_dir: "upload"
    avatar_dir: "%upload_dir%/avatar"

twig:
  globals:
    flash:
      error: "%flash_error_alias%"
      success: "%flash_success_alias%"
      warning: "%flash_warning_alias%"
      info: "%flash_info_alias%"
  form_themes:
    #    - 'bootstrap_3_horizontal_layout.html.twig'
    #    - 'form_themes/basic_form_theme.html.twig'
    - 'form_themes/col_md_6_form_theme.html.twig'

#paramaters:
#    upload_dir: "upload"
#    avatar_dir:
